name: Compile Sketch

on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - ./
          libraries: |
            - name: Preferences
              source-url: https://github.com/espressif/arduino-esp32.git
              source-path: ./libraries/Preferences/src
            - name: MFRC522
              source-url: https://github.com/miguelbalboa/rfid.git
            - name: u8x8
              source-url: https://github.com/olikraus/u8g2.git
              source-path: ./csrc
            - name: U8x8lib
              source-url: https://github.com/olikraus/u8g2.git
              source-path: ./cppsrc
